### ISSUE TITLE
Default to retry when FixedChannelPool was closed

### ISSUE THREAD

**Issue by Mkabaka** [esastack/esa-httpclient#119]
### Expected behavior
The request should be retried automatically when got `FixedChannelPool was closed`.

### Actual behavior
But in actuality, `IOException` was thrown.

```
Caused by: java.io.IOException: Error while acquiring connection
	at esa.httpclient.core.netty.NettyTransceiver.onAcquireConnectionFailed(NettyTransceiver.java:328)
	at esa.httpclient.core.netty.NettyTransceiver.handle0(NettyTransceiver.java:202)
	at esa.httpclient.core.netty.NettyTransceiver.lambda$handle$0(NettyTransceiver.java:157)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:501)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: java.lang.IllegalStateException: FixedChannelPool was closed
	at io.netty.channel.pool.FixedChannelPool$AcquireListener.operationComplete(FixedChannelPool.java:417)
	... 11 more
java.util.concurrent.ExecutionException: java.io.IOException: Error while acquiring connection
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at esa.http.protocol.client.esa.AppMain.lambda$main$0(AppMain.java:63)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Error while acquiring connection
	at esa.httpclient.core.netty.NettyTransceiver.onAcquireConnectionFailed(NettyTransceiver.java:328)
	at esa.httpclient.core.netty.NettyTransceiver.handle0(NettyTransceiver.java:202)
	at esa.httpclient.core.netty.NettyTransceiver.lambda$handle$0(NettyTransceiver.java:157)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:501)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: java.lang.IllegalStateException: FixedChannelPool was closed
	at io.netty.channel.pool.FixedChannelPool$AcquireListener.operationComplete(FixedChannelPool.java:417)
	... 11 more
```

### Env
- HttpClient version: v0.1.0
- JVM version: openjdk version "11.0.11"
- OS: win10

**Comment by Mkabaka** [comment]
There is no mentioned bug since v0.1.0.
